[theme]
backgroundColor = '#191414'
secondaryBackgroundColor = '#1DB954'
textColor = '#FFFFFF'
borderColor = '#1ED760'
primaryColor = '#1ED760'
showWidgetBorder = false
dataframeHeaderBackgroundColor = '#153613'

[theme.sidebar]
backgroundColor = '#404040'
secondaryBackgroundColor = '#191414'
showWidgetBorder = true
